edfunction jac = myfile(in1)
%MYFILE
%    JAC = MYFILE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    23-Mar-2020 13:07:23

x1 = in1(:,1);
x2 = in1(:,2);
t2 = x1+1.0./1.0e1;
jac = reshape([1.0,1.0./t2.^2.*x1.*-1.0e1+1.0e1./t2,0.0,x2.*4.0],[2,2]);
